project:
  type: website
website:
  title: "Data Interrogator"
  navbar:
    logo: logo.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/waseemwaheed
      - icon: linkedin
        href: https://www.linkedin.com/in/waseemwaheed/
format:
  html:
    theme: slate
    css: styles.css
execute:
  freeze: auto

