project:
  type: website
website:
  title: "Data Interrogator"
  site-url: https://blog.datainterrogator.org
  description: "This is Waseem Waheed's personal Blog."
  navbar:
    logo: logo.png
    right:
      - about.qmd
      - icon: github
        href: https://github.com/waseemwaheed
      - icon: linkedin
        href: https://www.linkedin.com/in/waseemwaheed/
  google-analytics: "G-K9LGM2ST2F"
format:
  html:
    theme: slate
    css: styles.css
execute:
  freeze: auto
cookie-consent: true
resources:
  - CNAME