---
title: "Learning Analytics - Dashboard with Google Data Studio"
author: "Waseem Waheed"
date: "2021-09-04"
categories: [data viz, Analytics]
---

COVID-19 has had a significant impact on our lives as a whole. Most industries have suffered from unexpected shift in customers demand. 

Few industries however have emerged unscathed from this pandemic, including retail, technology and health. 

Education has been on the industries hit very hard, and the result of this impact is yet to be fully understood. This could well be the beginning of an unprecedented transformation across the sector. 

LearnPlatform is a US based company that is specialized in EdTech, their mission is

> Expand equitable access for all students to teaching and education technology that works best for them.  [Source](https://learnplatform.com/about-us)

The company has a browser extension that collects data about usage of  EdTech tools. They have recently announced a competition of Kaggle aimed at better understanding and measuring the scope and impact of the pandemic on inequities in the system. The hypothesis is that the pandemic has increased those inequities which is a sad but reasonable hypothesis. 

The role of data analytics is to uncover the hidden realities in the data. That is not to say that the provided data set allows us to make any conclusion at this stage🤔. 

I have made an initial attempt to familiarize myself with the data by building a little and crude dashboard which can be accessed [here](https://datastudio.google.com/reporting/b9c802f2-76cb-41cf-8dc0-e6a5d309f52e). This dashboard gave me few questions to start exploring, so this is not the end (hopefully🤞).